# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# 平台：iOS，版本：9.0
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Shot' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shot
  pod 'Masonry'
  pod 'MBProgressHUD'

end


 